module.exports = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      items: ["welcome"],
    },
    {
      type: "category",
      label: "Git",
      items: [
        "git/git-intro",
        "git/git-intro-exercise",
        "git/git-branching-and-merging",
        "git/git-branching-and-merging-exercise",
        "git/git-merge-conflict-resolution",
        "git/git-merge-conflict-resolution-exercise",
      ],
    },
    {
      type: "category",
      label: "Introductions to Web Development",
      items: ["extras/internet-intro", "extras/intro-to-frontend"],
    },
    {
      type: "category",
      label: "HTML and CSS",
      items: [
        "html/html-intro",
        "html/html-intro-exercise",
        "css/css-intro",
        "css/css-intro-exercise",
        "html/html-forms-and-tables",
        "html/html-forms-and-tables-exercise",
        "css/css-flexbox-and-grid",
        "css/css-flexbox-and-grid-exercise",
      ],
    },
    {
      type: "category",
      label: "JavaScript",
      items: [
        "js/js-introduction-and-variables",
        "js/js-introduction-and-variables-exercise",
        "js/js-operators",
        "js/js-operators-exercise",
        "js/js-selection-statements",
        "js/js-selection-statements-exercise",
        "js/js-loops",
        "js/js-loops-exercise",
        "js/js-functions",
        "js/js-functions-exercise",
        "js/js-objects",
        "js/js-objects-exercise",
        "js/js-hof",
        "js/js-hof-exercise",
        "js/js-oop",
        "js/js-oop-exercise",
        "js/js-dom",
        "js/js-dom-exercise",
        "js/js-error-handling",
        "js/js-error-handling-exercise",
        "js/js-promises",
        "js/js-promises-exercise",
        "js/js-fetch-api",
        "js/js-fetch-api-exercise",
        "js/js-npm-yarn-webpack",
        "js/js-npm-yarn-webpack-exercise",
        "js/js-es6-modules",
        "js/js-es6-modules-exercise",
      ],
    },
    {
      type: "category",
      label: "React",
      items: [
        "react/react-intro",
        "react/react-intro-exercise",
        "react/react-state-props",
        "react/react-state-props-exercise",
        "react/react-lifecycle-methods",
        "react/react-lifecycle-methods-exercise",
        "react/react-hooks",
        "react/react-hooks-exercise",
        "react/react-router",
        "react/react-router-exercise",
        "react/react-router-hooks",
        "react/react-router-hooks-exercise",
      ],
    },
    {
      type: "category",
      label: "SQL",
      items: [
        "sql/sql-intro",
        "sql/sql-intro-exercise",
        "sql/sql-joins",
        "sql/sql-joins-exercise",
        "sql/sql-codewars-exercise",
      ],
    },
    {
      type: "category",
      label: "Node",
      items: [
        "node/node-intro",
        "node/node-intro-exercise",
        "node/node-http",
        "node/node-http-exercise",
        "node/node-fs",
        "node/node-fs-exercise",
        "node/node-events",
        "node/node-events-exercise",
        "node/node-streams",
        "node/node-streams-exercise",
        "node/node-reddit-exercise",
      ],
    },
    {
      type: "category",
      label: "Express.js",
      items: [
        "express/express-routing",
        "express/express-routing-exercise",
        "express/express-and-mysql",
        "express/express-and-mysql-exercise",
        "express/custom-api-project",
      ],
    },
    // {
    //   type: "category",
    //   label: "Beyond the Basics",
    //   items: [
    //     "beyond/environment-variables",
    //     "beyond/typescript-intro",
    //     "beyond/fullstack-template",
    //     "beyond/user-authentication",
    //   ],
    // },
  ],
};
